@extends('layouts.admin')
@section('title', 'Management Dashboard')
@section('page-title', 'DS / ADS / AO Management Dashboard')
@section('content')
<div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h3 mb-1">All-branch performance overview</h1><p class="text-muted mb-0">Monitor workloads, delays, completion, and officer assignments.</p></div><a href="{{ route('reports.index') }}" class="btn btn-primary"><i class="fa-solid fa-chart-line me-1"></i>Reports</a></div>
<div class="row g-3 mb-4">@foreach([['Branches',$branches->count(),'fa-building'],['Pending',$pendingCount,'fa-hourglass-half'],['Completed',$completedCount,'fa-circle-check'],['Delayed',$delayedCount,'fa-triangle-exclamation']] as [$label,$value,$icon])<div class="col-sm-6 col-xl-3"><div class="card soft-card h-100"><div class="card-body"><div class="metric-icon mb-3"><i class="fa-solid {{ $icon }}"></i></div><div class="text-muted">{{ $label }}</div><div class="fs-3 fw-bold">{{ $value }}</div></div></div></div>@endforeach</div>
<div class="row g-4 mb-4"><div class="col-xl-7"><div class="card soft-card h-100"><div class="card-body"><h2 class="h5">Monthly Applications</h2><canvas id="monthlyChart" height="115"></canvas></div></div></div><div class="col-xl-5"><div class="card soft-card h-100"><div class="card-body"><h2 class="h5">Officer Workload</h2>@forelse($officerWorkload as $officer)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $officer->name }}</span><span class="badge text-bg-primary">{{ $officer->workload }}</span></div>@empty<div class="text-muted">No officers assigned.</div>@endforelse</div></div></div></div>
<div class="card soft-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Branch</th><th>Total</th><th>Pending</th><th>Completed</th><th></th></tr></thead><tbody>@foreach($branches as $branch)<tr><td>{{ $branch->name }}</td><td>{{ $branch->applications_count }}</td><td><span class="badge text-bg-warning">{{ $branch->pending_count }}</span></td><td><span class="badge text-bg-success">{{ $branch->completed_count }}</span></td><td class="text-end"><a href="{{ route('branches.show', $branch) }}" class="btn btn-sm btn-outline-primary">View</a></td></tr>@endforeach</tbody></table></div></div>
@endsection
@push('scripts')<script>new Chart(document.getElementById('monthlyChart'),{type:'line',data:{labels:@json($monthlyApplications->keys()),datasets:[{data:@json($monthlyApplications->values()),borderColor:'#2563eb',backgroundColor:'rgba(37,99,235,.12)',fill:true,tension:.35}]},options:{plugins:{legend:{display:false}},responsive:true}});</script>@endpush
